# Generated by Django 5.1.5 on 2025-02-03 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_delete_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_reason',
            field=models.CharField(choices=[('1', 'General Inquiry'), ('2', 'Feedback'), ('3', 'Support')], default='1', max_length=1),
        ),
    ]
